packages:
  - .
  - cli
  - docs

ignoreDepScripts: true

ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@resvg/resvg-js'
  - better-sqlite3
  - sharp@0.34.5

overrides:
  sharp: 0.34.5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.12
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.12
  storybook: ^10.3.1

packageExtensions:
  '@nuxt/scripts':
    dependencies:
      estree-walker: ^3.0.3
  'unplugin-vue-markdown':
    peerDependencies:
      'vite': '^2.0.0 || ^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0 || ^6.0.0 || ^7.0.0 || ^8.0.0'

patchedDependencies:
  '@jsr/deno__doc@0.189.1': patches/@jsr__deno__doc@0.189.1.patch

savePrefix: ''

shellEmulator: true

catalogs:
  storybook:
    '@storybook-vue/nuxt': '9.0.1'
    '@storybook/addon-a11y': '^10.3.1'
    '@storybook/addon-docs': '^10.3.1'
    '@storybook/addon-themes': '^10.3.1'
    'storybook': '^10.3.1'
    'storybook-i18n': '^10.1.1'
